{% set name = "pyftdi" %}
{% set version = "0.52.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 21e84163a48057de9e4eba6efcb42e51994868b702e1eabdbd2a8cbddad66b66

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pyusb >=1.0.0
    - pyserial >=3.0

test:
  imports:
    - pyftdi.ftdi

about:
  home: https://github.com/eblot/pyftdi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: FTDI device driver written in pure Python
  description: |
    PyFtdi aims at providing a user-space driver for modern FTDI devices,
    implemented in pure Python language.
  doc_url: http://eblot.github.io/pyftdi/
  dev_url: https://github.com/eblot/pyftdi

extra:
  recipe-maintainers:
    - abloemert
